fix: add localized font families
RedHat-UX/red-hat-design-tokens pull request #139
Opened 2024-09-11 19:11 UTC by zeroedin

## What I did

1. Removed Noto Sans * font-families from base font-family stack
2. Created font-family stacks for each language using the [BCP 47](https://www.techonthenet.com/js/language_tags.php) for language tags to base the naming convention.  I used a shortened version instead of the full version unless necessary in the case of simplified and traditional chinese.  `zh-cn` and `zh-hk` respectively.

2024-09-12 16:28 UTC, bennypowers reviewed
LGTM just needs a changeset

You _might_ consider uppercasing the last two letters in the four letter codes

2024-09-24 21:33 UTC, zeroedin commented
> LGTM just needs a changeset
> 
> You _might_ consider uppercasing the last two letters in the four letter codes

Aded a changeset at `major`.  GIven we are changing the `rh-font-family-body-text && rh-font-family-heading` to values that would break current implementations without updates from users.

As far as uppercasing the last two letters in the tokens it appears the formatter lowercases them.  If we want to dig deeper into that we can.

2024-09-26 16:56 UTC, zeroedin commented
@benny can you add a request change blocker comment on this PR when you get a chance.  🥂

2024-09-26 16:58 UTC, bennypowers requested changes
The changes here look good, however there exists a problem which prevents us from merging at this time: it's a breaking change

Merging and releasing this in the RHDS clefairy release window would likely require a major bump for RHDS. This coming less than a month after the last breaking change, we will have to defer this.

It may be possible to find a non-breaking solution, but on short notice (as of this writing, about 1 workday left in the release cycle), we simply don't have the capacity to take such a decision

2024-10-08 14:45 UTC, bennypowers approved these changes

2024-10-08 14:45 UTC, bennypowers commented
Approved so this will be unblocked for you when you're ready @zeroedin, just make sure it gets a once-over

2024-10-08 14:45 UTC, bennypowers commented on .changeset/itchy-peas-report.md
> +"@rhds/tokens": major
```suggestion
"@rhds/tokens": patch
```

@markcaron told us he takes responsibility for breakabe

2024-10-08 14:57 UTC, merged