fix: change the value for the regular font weight for headings
RedHat-UX/red-hat-design-tokens pull request #143
Opened 2024-10-01 20:18 UTC by marionnegp

This closes #142

2024-10-03 06:41 UTC, coreyvickery requested changes
@marionnegp There is still some text with `300` under the `Font family` heading on the tokens demo page. Might want to get rid of that and then I will approve.

2024-10-04 16:05 UTC, coreyvickery approved these changes

2024-10-04 16:08 UTC, zeroedin requested changes
This will need a `patch` changeset.

2024-10-08 15:26 UTC, bennypowers approved these changes

2024-10-08 15:29 UTC, merged